AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 60

Metrics/MethodLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/ParameterLists:
  Max: 6
